// Everything that differs between the two themes lives here:
// the site title, the pictures or emoji for each agent, and every piece of wording.
// Past sessions are re-rendered from raw data, so switching themes relabels everything at once.

export const THEMES = [
  { id: "terminal", key: "T", label: "Terminal" },
  { id: "otter", key: "O", label: "Otter" },
];

// Otter theme pictures (files in frontend/public/otters/). Position them in styles.css, top block.
export const PICTURES = {
  ask: "/otters/yellow.png",
  business: "/otters/blue.png",
  eco: "/otters/pink.png",
  ethics: "/otters/green.png",
};

// Terminal theme emoji.
export const EMOJI = { ask: "💬", business: "🏢", eco: "🌿", ethics: "⚖️" };

export const TEXT = {
  terminal: {
    brand: "TriBunal Council",
    tagline: "Planning to use AI for a business task? The council finds a way to do it that cuts carbon without giving up the business value.",
    how: [
      "Describe what your company wants AI to do.",
      "Business, Environment and Tech & Ethics agents each vote and propose a win-win idea.",
      "Get the majority verdict and a plan that saves carbon while keeping what the business needs.",
    ],
    role: { business: "Business", eco: "Environment", ethics: "Tech & Ethics" },
    narrator: "Narrator",
    vote: { APPROVE: "APPROVE", REJECT: "REJECT", ABSTAIN: "ABSTAIN" },
    thinking: "THINKING",
    thinkingNote: "Weighing the facts",
    action: {
      FULL: ["FULL", "Run at full quality"],
      DOWNGRADE: ["DOWNGRADE", "Switch to the lightweight model"],
      CACHE: ["CACHE", "Reuse a cached answer"],
      BLOCK: ["BLOCK", "Stop: over today's budget"],
    },
    urgency: { Routine: "Routine", Emergency: "Emergency" },
    tally: (a, r, x) => `${a} approve, ${r} reject, ${x} abstain`,
    verdict: "Verdict",
    deliberating: "Deliberating",
    votesIn: "Votes in",
    failed: "The council could not meet",
    askTitle: "Your company's AI task",
    askLabel: "What does your company want to do with AI?",
    askHelp: "Say what the work is for and how often it runs. The council will look for a way to do it that keeps the business value and emits less carbon.",
    placeholder: "e.g. Every night, use AI to summarize 5,000 customer support tickets so the product team can spot recurring issues.",
    examples: "Or try an example",
    emergency: "Emergency (security, safety or a legal deadline: may go over the carbon budget)",
    convene: "Convene council",
    newQuestion: "New question",
    back: "Back to the last verdict",
    plan: "Win-win plan",
    idea: "Win-win idea",
    arguments: "Full arguments",
    result: "Result",
    working: "Running the request and recording the voices",
    audio: "Council audio",
    voices: "Individual voices",
    history: "History",
    clear: "Clear",
    cols: ["Time", "Case", "Urgency", "Votes", "Final", "Model", "CO₂ (g)", "Total (g)"],
    emptyTask: "Type a task for the council first.",
    gauge: (used, q) => `CO₂ today: ${used} / ${q} g (estimated)`,
    over: (g) => `, over by ${g} g after an emergency exception`,
    facts: (c) => `Estimated CO₂: full model ${c.est_full} g, lightweight ${c.est_lite} g. Remaining today: ${c.remaining.toFixed(1)} g.`,
    details: "Case details",
    titleLabel: "Short title (optional)",
    titlePlaceholder: "Defaults to the start of your task",
    titleHelp: "Shown in the history table and read aloud at the start of the session.",
    sizeLabel: "How big is the job? (tokens)",
    sizeHelp: "This demo doesn't upload real files, so set the size of the work here. Bigger jobs emit more: about 1 g of CO₂ per 1,000 tokens on the full-quality model, and a quarter of that on the lightweight one. A short email is about 500 tokens; a 50-page report is about 40,000.",
    set: {
      budget: (q) => `Daily carbon budget: ${q} g CO₂`,
      budgetHelp: "How much CO₂ your company allows AI work to emit today, shared by every request. A lower budget makes the council stricter: big jobs get switched to a lighter model, a cached answer, or blocked. For a demo, set it to 20-30 g to see the emergency exception in action.",
      peak: "Peak electricity hours",
      peakHelp: "Simulates running the job when the power grid is busiest and electricity is dirtier. Estimated emissions go up 1.5x, so the council is more likely to suggest a lighter model or running the job later.",
      voice: "Read the session aloud",
      voiceHelp: "ElevenLabs voices read the case, every agent's argument and idea, and the final verdict. Each agent has its own voice, and the voices change with the theme. Each session uses ElevenLabs credits, so turn this off for practice runs.",
      noVoice: " Unavailable: ELEVENLABS_API_KEY is not set.",
      about: (cfg) => `Agents: ${cfg.offline ? "offline mode, rule-based votes (no Gemini calls)" : "Gemini API"}. Full-quality model: ${cfg.models.full}. Lightweight model: ${cfg.models.lite}. All carbon figures are estimates for the demo, not measurements.`,
      reset: "Reset today's budget and history",
      resetHelp: "Sets today's CO₂ usage back to 0 g and clears the history table.",
    },
  },
  otter: {
    brand: "TriBunal Council",
    tagline: "Want AI to help with something? Ask the otters! They find a way that's fun for you and kind to the planet.",
    how: [
      "Tell the otters what you want AI to do.",
      "Three otters each say yes or nope, and share an idea.",
      "You get their answer and an easy plan.",
    ],
    role: { business: "Shop Keeper", eco: "Earth Buddy", ethics: "Fair Play" },
    narrator: "Storyteller",
    vote: { APPROVE: "YES!", REJECT: "NOPE", ABSTAIN: "PASS" },
    thinking: "THINKING...",
    thinkingNote: "Hmm, let me think",
    action: {
      FULL: ["Go big!", "Use the super smart AI"],
      DOWNGRADE: ["Go light!", "Use the little AI and save energy"],
      CACHE: ["Reuse it!", "Use an answer we already have"],
      BLOCK: ["Stop!", "Too big for today"],
    },
    urgency: { Routine: "Normal", Emergency: "Super urgent" },
    tally: (a, r, x) => `${a} yes, ${r} nope, ${x} pass`,
    verdict: "The otters say",
    deliberating: "The otters are chatting",
    votesIn: "Votes so far",
    failed: "The otters couldn't meet",
    askTitle: "Ask the otters",
    askLabel: "What should AI help with?",
    askHelp: "Tell us the job in a sentence or two.",
    placeholder: "e.g. Write a fun invitation for my friend's birthday picnic.",
    examples: "Or try one:",
    emergency: "It's super urgent!",
    convene: "Ask the otters",
    newQuestion: "Ask again",
    back: "See the last answer",
    plan: "Everybody-wins plan",
    idea: "Idea",
    arguments: "What each otter said",
    result: "What the AI made",
    working: "The AI is working and the otters are warming up their voices",
    audio: "Listen to the otters",
    voices: "Each otter",
    history: "Past answers",
    clear: "Clear",
    cols: ["Time", "Job", "Urgent?", "Votes", "Answer", "AI used", "Energy (g)", "Total (g)"],
    emptyTask: "Tell the otters what to do first!",
    gauge: (used, q) => `Energy used today: ${used} / ${q} g`,
    over: (g) => `, ${g} g extra for an emergency`,
    facts: (c) => `Big AI: ${c.est_full} g. Little AI: ${c.est_lite} g. Energy left today: ${c.remaining.toFixed(1)} g.`,
    details: "More options",
    titleLabel: "Give it a name (optional)",
    titlePlaceholder: "e.g. Birthday invite",
    titleHelp: "Shows up in Past answers.",
    sizeLabel: "How big is the job?",
    sizeHelp: "Bigger jobs use more energy. A short note is about 500. A long story is about 40,000.",
    set: {
      budget: (q) => `Energy for today: ${q} g`,
      budgetHelp: "How much energy AI can use today. Less energy means the otters say Go light! or Stop! more often.",
      peak: "Busy power time",
      peakHelp: "Pretend everyone is using power at once. Every job costs more, so the otters get pickier.",
      voice: "Let the otters talk",
      voiceHelp: "Hear each otter in its own voice. This uses ElevenLabs credits.",
      noVoice: " (Needs an ElevenLabs key.)",
      about: (cfg) => `Otter brains: ${cfg.offline ? "simple rules (offline)" : "Gemini"}. The numbers are pretend, just for the demo.`,
      reset: "Start fresh",
      resetHelp: "Fills today's energy back up and clears Past answers.",
    },
  },
};